### PR TITLE
English Translation Update

### PR DESCRIPTION
**Pull request by Jab005**
Added English (en-us) translation of this mod (temporary). Also updated some indonesian translation.

### CODE REVIEW

**Comment by Jab005** [comment]
I hope my translation is correct :skul:

**Comment by Jab005** [comment]
Shigure has updated the current file so i need to re-crosscheck after finished

**Review by WilloIzCitron — APPROVED** [review]
That's good

**Comment by Jab005** [comment]
I'll merge this for now so shigure can download the latest and update new translation using the new files

**Comment by Jab005** [comment]
No need to delete branch ig

**Pull request merged**
